### PR TITLE
Remove transformation

### PR DESCRIPTION
**Pull request by JarekW**

### CODE REVIEW

**Comment by JarekW** [comment]
@fsi-open

**Comment by szymach** [comment]
:+1:

**Comment by rn0** [comment]
:+1:

**Comment by JarekW** [comment]
@fsi-open

**Comment by JarekW** [comment]
@fsi-open should i create another pull request or it could stay?

**Comment by chives** [comment]
:+1:

**Comment by bartekgruszka** [comment]
:+1:

**Pull request merged**
