### PR TITLE
Update ruflin/elastica

### PR DESCRIPTION
**Pull request by chives**

### CODE REVIEW

**Comment by chives** [comment]
@fsi-open

**Comment by JarekW** [comment]
@rn0

**Comment by chives** [comment]
@JarekW we should add notice in the `README.md` that this driver requires ES ^2.0

**Comment by JarekW** [comment]
should we tag or create branch for what is currently on master, for those projects which use older EL?

**Comment by chives** [comment]
Last commit on `maser` is tagged `0.4.0`. After merging this PR we'll tag `0.5.0`. BC breaks are allowed between `0.x` releases, because `^0.4` requirement in `composer.json` won't install `0.5.0`.

**Comment by JarekW** [comment]
so we waiting for something? ;)

**Pull request merged**
